services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - ${HOST_POSTGRES_PORT}:5432
    env_file:
      - ../.env
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    networks:
      - app_network

  # postgres:
  #   image: pgvector/pgvector:pg15
  #   restart: unless-stopped
  #   expose:
  #     - 5432
  #   ports:
  #     - ${HOST_POSTGRES_PORT}:5432
  #   env_file:
  #     - ../.env
  #   volumes:
  #     - ../postgres/data:/var/lib/postgresql/data
  #   networks:
  #     - app_network

  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   expose:
  #     - 6379
  #   ports:
  #     - ${HOST_REDIS_PORT:-6379}:6379
  #   volumes:
  #     - ../redis/data:/data
  #   networks:
  #     - app_network
  #   command: redis-server --appendonly yes

  # mongodb:
  #   image: mongo:7.0
  #   restart: unless-stopped
  #   expose:
  #     - 27017
  #   ports:
  #     - ${HOST_MONGODB_PORT}:27017
  #   volumes:
  #     - ../mongodb/data:/data/db
  #   networks:
  #     - db_network

# volumes:
  # pg-data:
  # mongo-data:

networks:
  app_network:
    name: ${COMPOSE_PROJECT_NAME}_app_network
    driver: bridge
    external: false
